# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:
  media_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: feninea/kittygram_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
  frontend:
    image: feninea/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static_volume:/staticfiles
  nginx:
    image: feninea/kittygram_nginx  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
    ports:
      - 9000:80